// ─────────────────────────────────────────────────────────────────────
// BIE — Identity Layer
// Phase 4D S23 — Identity Layer Kickoff: Type & Interface Contracts (CANONICAL)
// ─────────────────────────────────────────────────────────────────────
//
// This file is the SINGLE source of truth for Identity Layer domain types.
// All consumers import FROM here; bie/types.ts re-exports for convenience.
//
// Hard constraints honored:
//   P4-8  Strict Widening Only — no removal of existing types.
//   P4-12 HITL: all identity update / insight proposals carry `applied: false`.
//   P4-2  Zero UX/UI change — this is type contracts only.
//
// Schema references: DECISIONS.md "BIE Storage Location", AI_ARCHITECTURE.md
// ─────────────────────────────────────────────────────────────────────

import type { LifeDimension } from "../../../types";

// ─────────────────────────────────────────────────────────────────────
// Shared enums / unions
// ─────────────────────────────────────────────────────────────────────

/**
 * Canonical 6-type insight classification for the Identity Layer.
 * Distinct from the broader `InsightKind` union in bie/types.ts —
 * this enum drives the InsightGenerator pipeline in S25.
 */
export type InsightType =
  | "reflection"
  | "pattern"
  | "milestone"
  | "gap"
  | "conflict"
  | "prediction";

/**
 * Timeline bucket granularity — month / quarter / year view.
 * Mirrors `TimelinePeriodKind` in bie/types.ts for identity-layer locality.
 */
export type TimelineGranularity = "month" | "quarter" | "year";

// ─────────────────────────────────────────────────────────────────────
// Identity Singleton
// ─────────────────────────────────────────────────────────────────────

/**
 * A single scored entry within an identity category (e.g. one core value).
 * `evidenceIds` link back to BrainEvidence records for traceability.
 */
export interface IdentityEntry {
  /** Human-readable label (Thai or English as authored). */
  label: string;
  /** 0-1 AI confidence derived from evidence weight & recency. */
  confidence: number;
  /** IDs of BrainEvidence records backing this entry. */
  evidenceIds: string[];
}

/**
 * Full identity profile aggregate across 8 canonical categories.
 * Singleton: exactly one row per user (`id = "singleton"`).
 *
 * HITL invariant (P4-12): `applied` MUST be `false` on every newly
 * generated profile until the user explicitly confirms in the Confirm UI.
 */
export interface IdentityProfile {
  /** Always "singleton" — one row per user in `bie_identity` table. */
  readonly id: "singleton";
  /** Core personal values (e.g. "freedom", "family", "growth"). */
  coreValues: IdentityEntry[];
  /** Active life goals with timeframe context. */
  goals: IdentityEntry[];
  /** Intrinsic motivations that drive behaviour. */
  motivations: IdentityEntry[];
  /** Personality traits (e.g. "introverted", "systematic"). */
  personality: IdentityEntry[];
  /** Observed personal strengths. */
  strengths: IdentityEntry[];
  /** Identified personal weaknesses / growth areas. */
  weaknesses: IdentityEntry[];
  /** Recurring thinking & decision-making patterns. */
  thinkingPattern: IdentityEntry[];
  /** Free-form AI-generated rollup summary paragraph. */
  summary: string;
  /** Unix ms timestamp of when this profile was generated. */
  generatedAt: number;
  /**
   * 🔒 ALWAYS `false` on creation (P4-12 HITL invariant).
   * Becomes `true` only after explicit User Confirm in the Confirm UI.
   */
  readonly applied: false;
}

/**
 * IndexedDB storage row for `bie_identity` table.
 * Extends IdentityProfile with a serialisable `applied` flag (db can store
 * boolean; the runtime domain type constrains it to `false` pre-confirm).
 */
export interface IdentityRow extends Omit<IdentityProfile, "applied"> {
  applied: boolean;
}

// ─────────────────────────────────────────────────────────────────────
// Insight Item
// ─────────────────────────────────────────────────────────────────────

/**
 * A single insight generated by the InsightGenerator engine (Phase 4D S25).
 * Stored in `bie_insights` (FIFO 100 cap).
 *
 * HITL invariant (P4-12): `applied` is a literal `false` on the domain
 * object — only the DB row (`InsightRow`) relaxes this to `boolean`.
 */
export interface InsightItem {
  /** UUID for the insight record. */
  id: string;
  /** 6-type classification driving display + filtering. */
  type: InsightType;
  /** Thai-language display title for the Confirm UI. */
  title: string;
  /** Thai-language descriptive body text. */
  description: string;
  /** 0-1 AI confidence score. */
  confidence: number;
  /**
   * Arbitrary structured metrics context (e.g. period, delta values, σ).
   * Typed as opaque Record for extensibility; concrete payloads defined per type.
   */
  dataContext: Record<string, unknown>;
  /** Unix ms timestamp of generation. */
  generatedAt: number;
  /**
   * 🔒 ALWAYS `false` (P4-12 HITL invariant).
   * Becomes `true` only after User Confirm.
   */
  readonly applied: false;
}

/**
 * IndexedDB storage row for `bie_insights` table.
 * Relaxes `applied` to `boolean` for DB serialisation.
 */
export interface InsightRow extends Omit<InsightItem, "applied"> {
  applied: boolean;
}

// ─────────────────────────────────────────────────────────────────────
// Timeline Entry
// ─────────────────────────────────────────────────────────────────────

/** Per-dimension thematic percentage within a timeline bucket. */
export interface TimelineThemeBreakdown {
  dimension: LifeDimension;
  /** 0-100 share of evidence within the bucket for this dimension. */
  percent: number;
  /** Tag IDs contributing to this dimension share. */
  tagIds: string[];
}

/** A notable milestone event anchored within a timeline bucket. */
export interface TimelineMilestoneEntry {
  id: string;
  label: string;
  /** Unix ms timestamp of when the milestone occurred. */
  occurredAt: number;
  dimension?: LifeDimension;
}

/**
 * One time bucket in the Life Timeline cache.
 * Stored in `bie_timeline` (rebuildable; contentHash invalidation).
 *
 * `contentHash` = SHA-1 of all contributing evidence IDs in this period.
 * On cache miss or hash mismatch → rebuild from evidence store.
 */
export interface TimelineEntry {
  /**
   * Period key (PK in bie_timeline). Examples:
   *   - Month:   "2026-05"
   *   - Quarter: "2026-Q2"
   *   - Year:    "2026"
   */
  periodKey: string;
  /** Granularity of this bucket. */
  granularity: TimelineGranularity;
  /** Dimension-by-dimension thematic breakdown for this period. */
  themeBreakdown: TimelineThemeBreakdown[];
  /** Notable milestones that occurred in this period. */
  milestones: TimelineMilestoneEntry[];
  /** Unix ms timestamp of when this entry was generated / last rebuilt. */
  generatedAt: number;
  /**
   * SHA-1 of all contributing evidence IDs for this period.
   * Used for cache invalidation — if evidence changes, hash changes → rebuild.
   */
  contentHash: string;
}

/**
 * IndexedDB storage row for `bie_timeline` table.
 * Structurally identical to TimelineEntry (timeline cache is not HITL-gated).
 */
export interface TimelineRow extends TimelineEntry {}
