// ─────────────────────────────────────────────────────────────────────
// BIE — Knowledge Graph Type & Schema Contracts
// Phase 4B S10 — Knowledge Graph + Relationship Engine Kickoff
// ─────────────────────────────────────────────────────────────────────
//
// Single source of truth for Knowledge Graph (KG) contracts, DB row shapes,
// and edge proposal queue structures.
//
// Hard Constraints:
//   P4-8  Strict Widening Only — additive additions only, no breaking changes.
//   P4-12 HITL Preserved — all edge proposals carry `applied: false` invariant.
//   P4-3  Edge Proposals — all edge creations are proposals only until confirmed.
// ─────────────────────────────────────────────────────────────────────

import type { LifeDimension, BrainType } from "../../../types";
import type { GraphEdgeType as LegacyGraphEdgeType, GraphNodeKind as LegacyGraphNodeKind, GraphNodeCoreType } from "../types";

/**
 * Widened Graph Node Category / Type.
 * Embraces both Core BIE kinds (person, fear, lesson, experience, milestone, tag)
 * and structural categories (Entity, Tag, Dimension, Evidence, Room, Insight).
 */
export type GraphNodeType =
  | "Entity"
  | "Tag"
  | "Dimension"
  | "Evidence"
  | "Room"
  | "Insight"
  | LegacyGraphNodeKind;

/**
 * Canonical 6 Edge Relationship Types per Phase 4B Specification:
 * - supports: Node A reinforces/supports Node B
 * - conflicts: Node A contradicts/conflicts with Node B
 * - causes: Node A causes/leads to Node B
 * - derived_from: Node A originates or stems from Node B
 * - related: General bidirectional semantic affinity
 * - opposes: Node A directly opposes or antagonizes Node B
 */
export type GraphEdgeType = LegacyGraphEdgeType;

/**
 * Domain Interface for a BIE Knowledge Graph Node.
 */
export interface BIEGraphNode {
  /** Primary Key: tag ID or `bie-node-<uuid>`. */
  id: string;
  /** Category / Kind of graph node. */
  nodeType: GraphNodeType;
  /** Human-readable node title/label. */
  label: string;
  /** Optional detailed context or description. */
  description?: string;
  /** Extended Brain Type if applicable. */
  coreType?: GraphNodeCoreType;
  /** Primary associated Life Dimension. */
  dimension?: LifeDimension;
  /** Arbitrary metadata key-value pairs. */
  metadata?: Record<string, unknown>;
  createdAt: number;
  updatedAt: number;
}

/**
 * Domain Interface for a BIE Knowledge Graph Edge.
 * Preserves structural HITL invariant `applied = false` by default.
 */
export interface BIEGraphEdge {
  /** Primary Key: edge ID. */
  id: string;
  /** Source node ID. */
  fromId: string;
  /** Target node ID. */
  toId: string;
  /** Relationship kind (one of 6 canonical edge types). */
  type: GraphEdgeType;
  /** AI confidence score [0.0 - 1.0]. */
  confidence: number;
  /** List of supporting evidence IDs backing this edge. */
  evidenceIds: string[];
  /** true if generated by AI proposal generator; false if created manually by user. */
  auto: boolean;
  /** 🔒 HITL Invariant: false until explicitly confirmed by User in UI. */
  applied: boolean;
  createdAt: number;
}

/**
 * Proposal object for introducing a new Knowledge Graph Edge.
 * Strictly enforces `applied: false` at the type level.
 */
export interface GraphEdgeProposal {
  /** Generated proposal ID (`bie-prop-<uuid>`). */
  id: string;
  fromId: string;
  toId: string;
  type: GraphEdgeType;
  confidence: number;
  reason: string;
  /** 🔒 STRUCTURAL INVARIANT: Must always be false upon proposal creation. */
  readonly applied: false;
  createdAt: number;
}

// ─────────────────────────────────────────────────────────────────────
// IndexedDB Storage Schema Contracts (bie_graph_nodes & bie_graph_edges)
// ─────────────────────────────────────────────────────────────────────

/**
 * Storage Row Shape for `bie_graph_nodes` table.
 *
 * Index Plan:
 * - Primary Key: `id` (string)
 * - Indices: `nodeType`, `dimension`, `coreType`
 */
export interface BIEGraphNodeRow {
  /** Primary Key: string. */
  id: string;
  /** Node category enum string. */
  nodeType: string;
  /** Display label. */
  label: string;
  /** Optional description text. */
  description?: string;
  /** Core BrainType string. */
  coreType?: string;
  /** LifeDimension string. */
  dimension?: string;
  /** JSON-serialized metadata object string. */
  metadataJson: string;
  createdAt: number;
  updatedAt: number;
}

/**
 * Storage Row Shape for `bie_graph_edges` table.
 *
 * Index Plan:
 * - Primary Key: `id` (string)
 * - Indices: `fromId`, `toId`, `type`, `applied` (for fast filtering of pending vs confirmed edges)
 */
export interface BIEGraphEdgeRow {
  /** Primary Key: string. */
  id: string;
  /** Source Node Foreign Key. */
  fromId: string;
  /** Target Node Foreign Key. */
  toId: string;
  /** Edge relationship type string. */
  type: string;
  /** Confidence score float [0.0 - 1.0]. */
  confidence: number;
  /** JSON-serialized array of evidence IDs (string[]). */
  evidenceIdsJson: string;
  /** Boolean stored as 1/0 or boolean depending on IndexedDB driver. */
  auto: boolean;
  /** 🔒 0 (false) until user confirmation in HITL screen. */
  applied: boolean;
  createdAt: number;
}

// ─────────────────────────────────────────────────────────────────────
// Entity Resolution & Duplicate Detection Types
// ─────────────────────────────────────────────────────────────────────

/**
 * Candidate pair for entity resolution or duplicate tag detection.
 */
export interface EntityResolutionCandidate {
  sourceNodeId: string;
  targetNodeId: string;
  /** Similarity / confidence score [0.0 - 1.0]. */
  matchScore: number;
  /** Match strategy identifier (e.g., "synonym_dict", "semantic_cosine", "levenshtein"). */
  similarityType: "synonym" | "semantic" | "fuzzy" | "exact";
  /** Explanation string for human review in HITL. */
  reason: string;
}

/**
 * Result of duplicate tag or entity resolution analysis.
 */
export interface DuplicateDetectionResult {
  primaryNodeId: string;
  duplicateNodeIds: string[];
  confidence: number;
  /** Summary diff for dry-run preview before user confirmation. */
  mergeDiffSummary: {
    evidencesToReassign: number;
    edgesToConsolidate: number;
  };
}
